<?php

namespace CovoiturageBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CovoiturageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CovoiturageRepository extends EntityRepository
{
    public function findCovoiturages()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM CovoiturageBundle:Covoiturage c WHERE c.date > CURRENT_DATE()");
        return $result = $query->getResult();
    }
    public function MesCovoiturages($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM CovoiturageBundle:Covoiturage c WHERE c.covoitureur=:i AND c.date > CURRENT_DATE()")
            ->setParameter('i', $id);

        return $result = $query->getResult();
    }

    public function MesAnciensCovoiturages($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM CovoiturageBundle:Covoiturage c WHERE c.covoitureur=:i AND c.date < CURRENT_DATE()")
            ->setParameter('i', $id);

        return $result = $query->getResult();
    }
    public function AutresCovoiturages($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM CovoiturageBundle:Covoiturage c WHERE c.covoitureur<>:i AND c.date > CURRENT_DATE()")
            ->setParameter('i', $id);

        return $result = $query->getResult();
    }

    /*public function findBesoin($p){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT s FROM bsitterBundle:besoin s WHERE s.idp like :e");
        //AND c.date > CURRENT_DATE()
        $query->setParameter('e', $p);
        return $query->getResult();
    }*/
}
