BabysittingBundle\Entity\Babysitting:
    type: entity
    table: null
    repositoryClass: BabysittingBundle\Repository\BabysittingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: '100'
        date:
            type: date
        heureDeb:
            type: time
        heureFin:
            type: time
        adresse:
            type: string
            length: 255
        description:
            type: string
            length: 255
        nbrEnfants:
            type: integer
    lifecycleCallbacks: {  }
