garderie_homepage:
    path:     /garderie
    defaults: { _controller: GarderieBundle:Default:index }
garderie_ajout:
    path:     /Ajoutgarderie
    defaults: { _controller: GarderieBundle:Garderies:ajout }
garderie_liste:
    path:     /listesgarderies
    defaults: { _controller: GarderieBundle:Garderies:list }
garderie_modifier:
    path:     /ModifierGarderie
    defaults: { _controller: GarderieBundle:Garderies:Update }
garderie_supprimer:
    path:     /SupprimerGarderie
    defaults: { _controller: GarderieBundle:Garderies:Delete }

