garderie_homepage:
    path:     /garderie
    defaults: { _controller: GarderieBundle:Default:index }
garderie_ajout:
    path:     /Ajoutgarderie
    defaults: { _controller: GarderieBundle:Garderies:ajout }
garderie_liste:
    path:     /listesgarderies
    defaults: { _controller: GarderieBundle:Garderies:list }
