security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_PARENT:       ROLE_USER
        ROLE_GARDERIE:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        admin_bundle:
            id: fos_user.admin_provider.username
    firewalls:
        admin:
            pattern:            ^/admin
            form_login:
                provider:       admin_bundle
                csrf_token_generator: security.csrf.token_manager
                login_path:     /admin
                check_path:     /admin/login_check
                default_target_path: /admin
                success_handler:  app.security.adminauthentication_handler
                failure_handler:  app.security.adminauthentication_handler
            logout:
                path:           /admin/logout
                target:         /admin
            anonymous:        true
            context:          application
        main:
            logout: ~
            pattern: ^/
            form_login:
                provider: fos_userbundle
                success_handler:  app.security.authentication_handler
                failure_handler:  app.security.authentication_handler
                csrf_token_generator: security.csrf.token_manager
            remember_me:
              secret: '%secret%'
            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/parent/, role: ROLE_PARENT }
        - { path: ^/garderie/, role: ROLE_GARDERIE }