activite_homepage:
    path:     /homepage
    defaults: { _controller: ActiviteBundle:Default:index }

activite_viewActivite:
    path:     /admin/activite/view
    defaults: { _controller: ActiviteBundle:Activite:viewActivite }

activite_createActivite:
    path:     /admin/activite/create
    defaults: { _controller: ActiviteBundle:Activite:createActivite }


activite_afficherActivite:
    path:     /admin/activite/afficher
    defaults: { _controller: ActiviteBundle:Activite:afficheBack }


activite_modifBackEnseignant:
    path:     /admin/ModificationActivite/{id}
    defaults: { _controller: ActiviteBundle:Activite:updateActivite  }

activite_updateActivite:
    path:     /admin/activite/update/{id}
    defaults: { _controller: ActiviteBundle:Activite:updateActivite }

activite_showActivite:
    path:     /admin/activite/show/{id}
    defaults: { _controller: ActiviteBundle:Activite:showActivite }

activite_deleteActivite:
    path:     /admin/activite/delete/{id}
    defaults: { _controller: ActiviteBundle:Activite:deleteActivite }





