<?php

namespace Proxies\__CG__\GarderieBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Garderies extends \GarderieBundle\Entity\Garderies implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'id', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'nom', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'adresse', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'telephone', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'descriptif', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'langues', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'dateOuverture', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'dateFermeture', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'rating', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'cout', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'nbInscriptions', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'heureDeb', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'heureFin', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'etat', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'image', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'email', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'longitude', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'latitude', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'proprietaire'];
        }

        return ['__isInitialized__', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'id', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'nom', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'adresse', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'telephone', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'descriptif', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'langues', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'dateOuverture', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'dateFermeture', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'rating', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'cout', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'nbInscriptions', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'heureDeb', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'heureFin', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'etat', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'image', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'email', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'longitude', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'latitude', '' . "\0" . 'GarderieBundle\\Entity\\Garderies' . "\0" . 'proprietaire'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Garderies $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptif($descriptif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptif', [$descriptif]);

        return parent::setDescriptif($descriptif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptif', []);

        return parent::getDescriptif();
    }

    /**
     * {@inheritDoc}
     */
    public function setLangues($langues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLangues', [$langues]);

        return parent::setLangues($langues);
    }

    /**
     * {@inheritDoc}
     */
    public function getLangues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLangues', []);

        return parent::getLangues();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOuverture($dateOuverture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOuverture', [$dateOuverture]);

        return parent::setDateOuverture($dateOuverture);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOuverture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOuverture', []);

        return parent::getDateOuverture();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFermeture($dateFermeture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFermeture', [$dateFermeture]);

        return parent::setDateFermeture($dateFermeture);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFermeture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFermeture', []);

        return parent::getDateFermeture();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating($rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', [$rating]);

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', []);

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setCout($cout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCout', [$cout]);

        return parent::setCout($cout);
    }

    /**
     * {@inheritDoc}
     */
    public function getCout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCout', []);

        return parent::getCout();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureDeb($heureDeb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureDeb', [$heureDeb]);

        return parent::setHeureDeb($heureDeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureDeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureDeb', []);

        return parent::getHeureDeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureFin($heureFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureFin', [$heureFin]);

        return parent::setHeureFin($heureFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureFin', []);

        return parent::getHeureFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setProprietaire(\FrontBundle\Entity\User $proprietaire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProprietaire', [$proprietaire]);

        return parent::setProprietaire($proprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getProprietaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProprietaire', []);

        return parent::getProprietaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbInscriptions($nbInscriptions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbInscriptions', [$nbInscriptions]);

        return parent::setNbInscriptions($nbInscriptions);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbInscriptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbInscriptions', []);

        return parent::getNbInscriptions();
    }

}
