medecin_homepage:
    path:     /
    defaults: { _controller: MedecinBundle:Default:index }
medecin_ajout:
    path:     /Ajoutmedecin
    defaults: { _controller: MedecinBundle:Medecin:ajout }
medecin_liste:
    path:     /listesmedecins
    defaults: { _controller: MedecinBundle:Medecin:list }
medecin_modifier:
    path:     /Modifiermedecins
    defaults: { _controller: MedecinBundle:Medecin:Update }
medecin_supprimer:
    path:     /Supprimermedecin
    defaults: { _controller: MedecinBundle:Medecin:Delete }
demande_afficher2:
    path:     /listesgarderiesFront
    defaults: { _controller: MedecinBundle:Medecin:listeDemandes}
demande_supprimer2:
    path:     /SupprimerDemande
    defaults: { _controller: MedecinBundle:Medecin:DeleteDemande}
demande_accepter2:
    path:     /AccepterDemande
    defaults: { _controller: MedecinBundle:Medecin:AccepterDemande}
garderie_listeFront2:
    path:     /garderieList
    defaults: { _controller: MedecinBundle:Medecin:listFront }
garderie_details:
    path:     /garderiedetails
    defaults: { _controller: MedecinBundle:Medecin:DetailsGarderies }
garderie_inscription:
    path:     /garderieinscription
    defaults: { _controller: MedecinBundle:Medecin:Inscription }
