<?php

namespace ELearningBundle\Repository;

/**
 * DemandeInscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeInscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function AllDemande($idm)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT d From ELearningBundle:DemandeInscription d where  d.medecinId =:idmedecin and d.etat='ATTENTE' ");
        $query->setParameter('idmedecin', $idm);
        return  $query->getResult();
    }
    public function AccepterDemande($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("UPDATE ELearningBundle:DemandeInscription d SET  d.etat='ACCEPTE' WHERE d.id=:id");
        $query->setParameter('id', $id);
        return  $query->execute();
    }
    public function RefuserDemande($id)
    {
        $query=$this->getEntityManager($id)
            ->createQuery("DELETE FROM ELearningBundle:DemandeInscription d WHERE d.id=:id");
        $query->setParameter('id', $id);
        return  $query->execute();
    }
    public function DemandeAccepte($idm)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT d From ELearningBundle:DemandeInscription d where  d.medecinId =:idmedecin and d.etat='ACCEPTE' ");
        $query->setParameter('idmedecin', $idm);
        return  $query->getResult();

    }
}
