<?php

namespace ELearningBundle\Repository;

/**
 * EnfantMaladeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantMaladeRepository extends \Doctrine\ORM\EntityRepository
{
}
