<?php

namespace BabysittingBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * BabysittingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BabysittingRepository extends EntityRepository
{
    public function MesBabysittings($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM BabysittingBundle:Babysitting c WHERE c.babysitteur=:i AND c.date > CURRENT_DATE()")
            ->setParameter('i', $id);

        return $result = $query->getResult();
    }

    public function MesAnciensBabysittings($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM BabysittingBundle:Babysittinge c WHERE c.babysitteur=:i AND c.date < CURRENT_DATE()")
            ->setParameter('i', $id);

        return $result = $query->getResult();
    }
    public function AutresBabysittings($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM BabysittingBundle:Babysitting c WHERE c.babysitteur<>:i AND c.date > CURRENT_DATE()")
            ->setParameter('i', $id);

        return $result = $query->getResult();
    }

    public function CurrentBabysittings()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM BabysittingBundle:Babysitting c WHERE  c.date > CURRENT_DATE()");
        return $result = $query->getResult();
    }
}
