<?php

namespace BabysittingBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * BabysittingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BabysittingRepository extends EntityRepository
{
}
