publicite_index:
    path:     /publicite
    defaults: { _controller: "BackOfficeBundle:Publicite:index" }
    methods:  GET

publicite_show:
    path:     /publicite/{id}/show
    defaults: { _controller: "BackOfficeBundle:Publicite:show" }
    methods:  GET

publicite_new:
    path:     /publicite/new
    defaults: { _controller: "BackOfficeBundle:Publicite:new" }
    methods:  [GET, POST]

publicite_edit:
    path:     /publicite/{id}/edit
    defaults: { _controller: "BackOfficeBundle:Publicite:edit" }
    methods:  [GET, POST]

publicite_delete:
    path:     /publicite/{id}/delete
    defaults: { _controller: "BackOfficeBundle:Publicite:delete" }
    methods:  DELETE
