e_learning_homepage:
    path:     /Ens
    defaults: { _controller: ELearningBundle:Default:index }
e_learning_afficherEnseignant:
    path:     /affichEnseignant
    defaults: { _controller: ELearningBundle:Default:affiche }
e_learning_affecterEnfant:
    path:     /affecterEnseignant/{idm}/{idp}
    defaults: { _controller: ELearningBundle:DemandeInscription:ajout }
e_learning_afficherBackEnseignant:
    path:     /admin/affichbackEnseignant
    defaults: { _controller: ELearningBundle:Default:afficheBack }
e_learning_ajouterBackEnseignant:
    path:     /admin/ajoutbackEnseignant
    defaults: { _controller: ELearningBundle:Default:Ajout }
e_learning_modifBackEnseignant:
    path:     /admin/ModificationEnseignant/{id}
    defaults: { _controller: ELearningBundle:Default:modif }
e_learning_suppBackEnseignant:
    path:     /admin/SupprimerEnseignant
    defaults: { _controller: ELearningBundle:Default:supp }
e_learning_afficherDemande:
    path:     /afficherDemande
    defaults: { _controller: ELearningBundle:DemandeInscription:afficheDemandeEnseignant}
e_learning_accepterDemande:
    path:     /accepterDemande
    defaults: { _controller: ELearningBundle:DemandeInscription:AccepterDemande}
e_learning_RefuserDemande:
    path:     /refuserDemande
    defaults: { _controller: ELearningBundle:DemandeInscription:RefuserDemande}
Calendar:
    path:     /calendar
    defaults: { _controller: ELearningBundle:DemandeInscription:calendar}
