<?php

namespace RecetteBundle\Repository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function  verif($user_id,$recette_id)
    {
        $query = $this->getEntityManager()
            ->createQuery("
            select v from RecetteBundle:Vote v 
            WHERE v.userId=:user_id 
            AND v.recetteId=:recette_id 
            ");
        $query->setParameter('user_id', $user_id);
        $query->setParameter('recette_id',$recette_id);
        if ($query->getResult()){
            return true;
        }
        return false;
    }
 public function UpdateLike($user_id,$recette_id)
 {
     $query=$this->getEntityManager()
         ->createQuery('UPDATE RecetteBundle:Vote v SET v.vote = 1 WHERE v.userId=:user_id AND v.recetteId=:recette_id');
     $query->setParameter('user_id', $user_id);
     $query->setParameter('recette_id',$recette_id);
     $query->execute();
 }
    public function UpdateDislike($user_id,$recette_id)
    {
        $query=$this->getEntityManager()
            ->createQuery('UPDATE RecetteBundle:Vote v SET v.vote =-1 WHERE v.userId=:user_id AND v.recetteId=:recette_id');
        $query->setParameter('user_id', $user_id);
        $query->setParameter('recette_id',$recette_id);
        $query->execute();
    }
    public function AddLikeToRecette($recette_id)
    {
        $query=$this->getEntityManager()
            ->createQuery('UPDATE RecetteBundle:Recette r SET r.likeCount = r.likeCount + 1 WHERE r.id=:recette_id');
        $query->setParameter('recette_id',$recette_id);
        $query->execute();
    }
    public function AddDisLikeToRecette($recette_id){
        $query=$this->getEntityManager()
            ->createQuery('UPDATE RecetteBundle:Recette r SET r.dislikeCount = r.dislikeCount + 1 WHERE r.id=:recette_id');
        $query->setParameter('recette_id',$recette_id);
        $query->execute();

    }
    public function RemoveLikeToRecette($recette_id){
        $query=$this->getEntityManager()
            ->createQuery('UPDATE RecetteBundle:Recette r SET r.likeCount = r.likeCount - 1 WHERE r.id=:recette_id');
        $query->setParameter('recette_id',$recette_id);
        $query->execute();
    }
    public function RemoveDislikeToRecette($recette_id){
        $query=$this->getEntityManager()
            ->createQuery('UPDATE RecetteBundle:Recette r SET r.dislikeCount = r.dislikeCount - 1 WHERE r.id=:recette_id');
        $query->setParameter('recette_id',$recette_id);
        $query->execute();

    }

}
