<?php

namespace Proxies\__CG__\BabysittingBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Babysitting extends \BabysittingBundle\Entity\Babysitting implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'id', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'titre', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'date', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'heureDeb', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'heureFin', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'adresse', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'description', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'nbrEnfants', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'babysitteur'];
        }

        return ['__isInitialized__', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'id', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'titre', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'date', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'heureDeb', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'heureFin', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'adresse', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'description', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'nbrEnfants', '' . "\0" . 'BabysittingBundle\\Entity\\Babysitting' . "\0" . 'babysitteur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Babysitting $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getBabysitteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBabysitteur', []);

        return parent::getBabysitteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setBabysitteur($babysitteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBabysitteur', [$babysitteur]);

        return parent::setBabysitteur($babysitteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureDeb($heureDeb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureDeb', [$heureDeb]);

        return parent::setHeureDeb($heureDeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureDeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureDeb', []);

        return parent::getHeureDeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureFin($heureFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureFin', [$heureFin]);

        return parent::setHeureFin($heureFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureFin', []);

        return parent::getHeureFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrEnfants($nbrEnfants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrEnfants', [$nbrEnfants]);

        return parent::setNbrEnfants($nbrEnfants);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrEnfants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrEnfants', []);

        return parent::getNbrEnfants();
    }

}
