<?php

namespace Proxies\__CG__\CovoiturageBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Covoiturage extends \CovoiturageBundle\Entity\Covoiturage implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'id', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'date', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'titre', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'nbPlaces', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'heureDep', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'lieuDep', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'lieuDest', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'description', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'voiture', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'covoitureur'];
        }

        return ['__isInitialized__', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'id', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'date', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'titre', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'nbPlaces', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'heureDep', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'lieuDep', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'lieuDest', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'description', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'voiture', '' . "\0" . 'CovoiturageBundle\\Entity\\Covoiturage' . "\0" . 'covoitureur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Covoiturage $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbPlaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbPlaces', []);

        return parent::getNbPlaces();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbPlaces($nbPlaces)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbPlaces', [$nbPlaces]);

        return parent::setNbPlaces($nbPlaces);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureDep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureDep', []);

        return parent::getHeureDep();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureDep($heureDep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureDep', [$heureDep]);

        return parent::setHeureDep($heureDep);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuDep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuDep', []);

        return parent::getLieuDep();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuDep($lieuDep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuDep', [$lieuDep]);

        return parent::setLieuDep($lieuDep);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuDest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuDest', []);

        return parent::getLieuDest();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuDest($lieuDest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuDest', [$lieuDest]);

        return parent::setLieuDest($lieuDest);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getVoiture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVoiture', []);

        return parent::getVoiture();
    }

    /**
     * {@inheritDoc}
     */
    public function setVoiture($voiture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVoiture', [$voiture]);

        return parent::setVoiture($voiture);
    }

    /**
     * {@inheritDoc}
     */
    public function getCovoitureur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCovoitureur', []);

        return parent::getCovoitureur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCovoitureur($covoitureur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCovoitureur', [$covoitureur]);

        return parent::setCovoitureur($covoitureur);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

}
