<?php

namespace Proxies\__CG__\GarderieBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Inscription extends \GarderieBundle\Entity\Inscription implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'id', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'nomparent', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'adresse', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'commentaires', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'nurserie', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'repas', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'etat', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'jourArriv', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'idEnfant', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'idParent', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'idGarderie'];
        }

        return ['__isInitialized__', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'id', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'nomparent', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'adresse', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'commentaires', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'nurserie', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'repas', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'etat', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'jourArriv', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'idEnfant', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'idParent', '' . "\0" . 'GarderieBundle\\Entity\\Inscription' . "\0" . 'idGarderie'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Inscription $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomparent($nomparent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomparent', [$nomparent]);

        return parent::setNomparent($nomparent);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomparent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomparent', []);

        return parent::getNomparent();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaires($commentaires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaires', [$commentaires]);

        return parent::setCommentaires($commentaires);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaires', []);

        return parent::getCommentaires();
    }

    /**
     * {@inheritDoc}
     */
    public function setNurserie($nurserie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNurserie', [$nurserie]);

        return parent::setNurserie($nurserie);
    }

    /**
     * {@inheritDoc}
     */
    public function getNurserie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNurserie', []);

        return parent::getNurserie();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepas($repas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepas', [$repas]);

        return parent::setRepas($repas);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepas', []);

        return parent::getRepas();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setJourArriv($jourArriv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJourArriv', [$jourArriv]);

        return parent::setJourArriv($jourArriv);
    }

    /**
     * {@inheritDoc}
     */
    public function getJourArriv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJourArriv', []);

        return parent::getJourArriv();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEnfant(\FrontBundle\Entity\Enfant $idEnfant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEnfant', [$idEnfant]);

        return parent::setIdEnfant($idEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEnfant', []);

        return parent::getIdEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdParent(\FrontBundle\Entity\User $idParent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdParent', [$idParent]);

        return parent::setIdParent($idParent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdParent', []);

        return parent::getIdParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGarderie(\GarderieBundle\Entity\Garderies $idGarderie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGarderie', [$idGarderie]);

        return parent::setIdGarderie($idGarderie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGarderie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGarderie', []);

        return parent::getIdGarderie();
    }

}
